version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build-docker:
    docker:
      - image: docker:29.6-dind
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login to be able to push images
          command: |
            apk add --no-cache wget tar
            wget https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/latest/download/docker-credential-gcr_linux_amd64-2.1.32.tar.gz
            tar xz docker-credential-gcr_linux_amd64.tar.gz
            sudo mv docker-credential-gcr /usr/local/bin
            echo "$GCLOUD_SERVICE_KEY" > /tmp/gcp-key.json
            export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json
            docker-credential-gcr configure-docker --registries=us-west4-docker.pkg.dev

      - run:
          name: Build/Push Janus Gateway
          command: |
            docker build -t us-west4-docker.pkg.dev/$GOOGLE_PROJECT_ID/backend/janus-gateway:$CIRCLE_WORKFLOW_ID ./janus_gateway
            docker push us-west4-docker.pkg.dev/$GOOGLE_PROJECT_ID/backend/janus-gateway:$CIRCLE_WORKFLOW_ID

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - build-docker:
          filters:
            branches:
              only: [ main ]
