version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build-docker:
    docker:
      - image: docker:17.09-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login to be able to push images
          command: |
            apk add --no-cache bash curl python3 libc6-compat ca-certificates tar
            curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz
            tar -xzf google-cloud-cli-linux-x86_64.tar.gz
            ./google-cloud-sdk/install.sh --quiet
            rm google-cloud-cli-linux-x86_64.tar.gz
            echo "$GCLOUD_SERVICE_KEY" > "$HOME/key.json"
            gcloud auth activate-service-account --key-file="$HOME/key.json"
            gcloud config set project "$GOOGLE_PROJECT_ID"
            gcloud auth configure-docker us-west4-docker.pkg.dev --quiet
      - run:
          name: Build/Push Janus Gateway
          command: |
            docker build -t us-west4-docker.pkg.dev/$GOOGLE_PROJECT_ID/backend/janus-gateway:$CIRCLE_WORKFLOW_ID ./janus_gateway
            docker push us-west4-docker.pkg.dev/$GOOGLE_PROJECT_ID/backend/janus-gateway:$CIRCLE_WORKFLOW_ID

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - build-docker:
          filters:
            branches:
              only: [ main ]
